name = "dht-test-plan"

[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
build_base_image = "golang:1.19-buster"
go_version = "1.19"
module_path = "github.com/ChainSafe/dht-test-plan"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/ChainSafe/dht-test-plan"
exec_pkg = "."

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[[testcases]]
name = "find-providers"
instances = { min = 1, max = 10000, default = 1 }